"""well type removed

Revision ID: 7b02e1357a39
Revises: 84f46aeeeb31
Create Date: 2025-03-05 09:52:25.926738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b02e1357a39'
down_revision = '84f46aeeeb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_well', schema=None) as batch_op:
        batch_op.drop_column('well_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_well', schema=None) as batch_op:
        batch_op.add_column(sa.Column('well_type', sa.VARCHAR(length=5), nullable=False))

    # ### end Alembic commands ###
